# Site settings
title: Giovanni Bindi
header-img: img/home-bg.jpg
email: giovanni.bindi@gmail.com
copyright_name: Giovanni Bindi
description: "Personal website"
baseurl: ""
url: "http://tongatron.it"
twitter_username: giobindi
github_username:  tongatron
facebook_username:  giovanni.bindi
email_username:  giovanni.bindi@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
